### ISSUE TITLE
Custom sorting function will break super-groups

### ISSUE THREAD

**Issue by thorbenandresen** [alphapapa/org-ql#217]
This works fine `*`:

``` elisp
 (org-ql-search (org-agenda-files)
    '(todo)
  :sort '(todo)
  :super-groups '((:auto-parent t)))

```
This does not work fine:

``` elisp
 (org-ql-search (org-agenda-files)
    '(todo)
    :sort '(lambda (x y)
             (string< (org-element-property :todo-keyword y) (org-element-property :todo-keyword x))
             ))
  :super-groups '((:auto-parent t)))

```
The todo items are sorted correct but are no longer grouped by the parent

Is this expected or a bug?

Btw. I love this package and it has become an indispensable part of my daily workflow!

---
`*` Well not really. Let me explain my intention to avoid the [XY Problem](https://xyproblem.info/): I am actually trying to sort the todo items within the groups by the todo state based on the position of the `org-todo-keywords` sequence (instead of alphabetical sorting). I know that my custom sorting function above sorts alphabetically (I wanted to keep my example simple)

**Comment by alphapapa** [comment]
> I am actually trying to sort the todo items within the groups by the todo state based on the position of the org-todo-keywords sequence (instead of alphabetical sorting).

This is already implemented: see https://github.com/alphapapa/org-ql/blob/208e103ecc146db71d878df3bd09c6eb60c2797d/org-ql.el#L1886.

> The todo items are sorted correct but are no longer grouped by the parent.  Is this expected or a bug?

I'm not aware of custom sorters breaking grouping.  If it does, that would be a bug, but I don't know how it could have that effect.

BTW, you don't need to quote lambdas, and shouldn't.

> Btw. I love this package and it has become an indispensable part of my daily workflow!

Thanks, I'm glad to hear it.

**Comment by alphapapa** [comment]
BTW, it's possible this is related to #186, which I'll soon push a fix for.

**Comment by alphapapa** [comment]
That issue is fixed.  Please let me know if it fixes the problem for you.

**Comment by thorbenandresen** [comment]
> > I am actually trying to sort the todo items within the groups by the todo state based on the position of the org-todo-keywords sequence (instead of alphabetical sorting).
> 
> This is already implemented: see
> 
> https://github.com/alphapapa/org-ql/blob/208e103ecc146db71d878df3bd09c6eb60c2797d/org-ql.el#L1886

I still have problems with sorting by the position in the `org-todo-keyword` sequence

For example...

``` elisp
(defun ta/org-ql/low-energy-task ()
  (interactive)
  (org-ql-search (org-agenda-files)
    '(tags "LET")
    :sort '(todo)
    :super-groups '((:auto-parent t))
    :title "Low Energy Task")
  )
```

``` elisp
 ( setq org-todo-keywords '(
                             (sequence
                              "URGENT(u)"
                              "NEXT(1)"
                              "P2(2)"
                              "P3(3)"
                              "TODO(t)"
                              "|"
                              "DONE(x)"
                              )))
```

...will produce a list wich is not sorted as intended
<img width="629" alt="image" src="https://user-images.githubusercontent.com/8238976/128647570-dcdbab44-27dd-45a7-906e-0616cffb7063.png">

org-ql 0.5.2
GNU Emacs 27.2 (build 1, aarch64-apple-darwin20.4.0, NS appkit-2022.44 Version 11.3 (Build 20E232)) of 2021-05-07

**Comment by alphapapa** [comment]
In the code I linked earlier, you can see that the variable `org-todo-keywords-1` is used, not `org-todo-keywords`.  The `-1` variable is set by Org itself when a file is opened and the mode is activated, because those keywords can be set in each file with keywords.

**Comment by thorbenandresen** [comment]
Thank you for the clarification, but I still have issues with this, LMK if I should open a separate issue. 

The value of `org-todo-keywords-1` is consistent with `org-todo-keywords`, yet the sorting does not work as intended. 

I tried now to remove my custom `org-todo-keywords` value and solely used the file-based definition via `#+TODO:`. However the sorting is still off:

```elisp
(defun ta/org-ql/low-energy-task ()
  (interactive)
  (org-ql-search "~/Dropbox/org/gtd/gtd.org"
    '(tags "LET")
    :sort '(todo)
    :super-groups '((:auto-parent t))
    :title "Low Energy Task")
  )
```

![screen shot 2021-08-09 at 11 06 53 PM](https://user-images.githubusercontent.com/8238976/128775340-a02b804c-b0f1-4343-a220-05d23eb49542.jpg)

Will result in:

![screen shot 2021-08-09 at 11 08 01 PM](https://user-images.githubusercontent.com/8238976/128775395-137aab86-4f05-41b3-8ae3-8e3113a9032f.jpg)

Do you have any ideas how to debug this?

**Comment by alphapapa** [comment]
Did you reinitialize org-mode in that buffer?  i.e. if you `C-c C-c` on a `#+TODO:` header, it should reset that variable.

If it still doesn't work correctly after doing that, please do open a new issue, because it might be something peculiar to todo-keyword sorting.  Thanks.
